% Thermal Simulation of a Multi-Layer Powder Bed with Moving Laser Heat Source
% This script simulates the temperature evolution in a powder bed during laser scanning
% and visualizes the heat trail left by the laser on the top surface.

% Step 1: Initialize the Thermal Model
thermalModel = createpde('thermal', 'transient');


% Step 2: Define the Multi-Layer Geometry A multi layer Geometry is
% Constructed using multicuboid,with layers represented by sepcific
% thickness and Offsets 
length = 4e-3;            % Length of the powder bed (4 mm)
width = 0.5e-3;           % Width of the powder bed (0.5 mm)
layerThickness = 0.02e-3; % Thickness of each layer (0.02 mm)

% Define heights for bottom and top layers
bottomHeight = 10 * layerThickness; % Height of the bottom bulk layer (10 layers)
topHeight = layerThickness;         % Height of the top powder layer (1 layer)

% Heights and offsets
layerHeights = [bottomHeight, topHeight]; % Heights of bottom and top layers
zOffsets = [0, bottomHeight];             % Z-offset for the top layer

% Use multicuboid to define the geometry with multiple cells
globalGeometry = multicuboid(length, width, layerHeights, 'ZOffset', zOffsets);

% Visualize the geometry with face labels
figure;
pdegplot(globalGeometry, 'FaceLabels', 'on', 'FaceAlpha', 0.5);
title('Geometry with Face Labels');
xlabel('X [m]');
ylabel('Y [m]');
zlabel('Z [m]');
view(30, 30);

% Assign the geometry to the thermal model
thermalModel.Geometry = globalGeometry;

%Step 3: Mesh. As we change the value of mesh it takes more time. As
% mentioned in the prorgam the mesh value is below 0.003e
% it take more computational power resulting more time genrating output in my case I never got one
generateMesh(thermalModel, 'Hmax', 0.03e-3); % Finer mesh for improved accuracy

% Step 4: Define Thermal Properties

% Define thermal properties for Cell 1 (bottom bulk layer)
thermalProperties(thermalModel, 'Cell', 1, ...
    'ThermalConductivity', @thermalConductivity, ...
    'MassDensity', 8440, ...
    'SpecificHeat', @specificHeat);

% % Step 4: Define Thermal Properties The value 0.1 W/(m·K) is used as an example for the powder material.
%This specifies the density of the powder material, set to 2500 kg/m³. This parameter impacts the thermal inertia of the material.
%hese properties directly influence the thermal behavior of the top layer during laser exposure (top powder layer)
thermalProperties(thermalModel, 'Cell', 2, ...
    'ThermalConductivity', 0.1, ... % Thermal conductivity for powder (W/(m*K))
    'MassDensity', 2500, ...        % Density for powder (kg/m^3)
    'SpecificHeat', 800);           % Specific heat for powder (J/(kg*K))

% Step 5: Apply Boundary Conditions

%%THE Bottom Layer
%THe Boundary conditions define how the heat interacts with the
%surface.As we have considered there are 11 layer. the base face 1 has a
%constant temp. of 353 K due to which the environment remains stable and
%due to which we keep the controlled temperature at the bottom

thermalBC(thermalModel, 'Face', 1, 'Temperature', 353); % Base held at 353 K

%%The Top Layer 
% Heat Flux Condition:
% - The top face (Face 7) experiences heat flux generated by the ‘laserHeatSource’ function.
% - This simulates the energy input from a moving laser heating the top layer, mimicking real-world laser processes.
% - These boundary conditions help create a realistic thermal simulation by modeling how heat interacts with the powder bed during processing.

% Apply heat flux boundary condition on the top surface (Face 7)
thermalBC(thermalModel, 'Face', 7, 'HeatFlux', @laserHeatSource);

% Step 6: Set Initial Conditions
thermalIC(thermalModel, 293); % Initial ambient temperature (293 K)

% Step 7: Define Time Steps for Laser Movement
tlist = linspace(0, 0.004, 100); % Simulation duration from 0 to 0.004 seconds

% Step 8: Solve the Thermal Model
results = solve(thermalModel, tlist);

% Step 9: Post-Processing to Calculate Melt Pool Dimensions
Tl = 1623; % Liquidus temperature in K
temperatureData = results.Temperature(:, end);

% Identify nodes where the temperature exceeds the liquidus temperature
meltPoolNodes = find(temperatureData >= Tl);
xCoords = thermalModel.Mesh.Nodes(1, meltPoolNodes);
yCoords = thermalModel.Mesh.Nodes(2, meltPoolNodes);
zCoords = thermalModel.Mesh.Nodes(3, meltPoolNodes);

% Calculate melt pool dimensions
meltPoolLength = max(xCoords) - min(xCoords); % Length in x-direction
meltPoolWidth = max(yCoords) - min(yCoords);  % Width in y-direction
meltPoolDepth = max(zCoords) - min(zCoords);  % Depth in z-direction

% Convert dimensions to millimeters
meltPoolLength_mm = meltPoolLength * 1e3;
meltPoolWidth_mm = meltPoolWidth * 1e3;
meltPoolDepth_mm = meltPoolDepth * 1e3;

% Display melt pool dimensions
fprintf('Melt Pool Length (MPL): %.4f mm\n', meltPoolLength_mm);
fprintf('Melt Pool Width (MPW): %.4f mm\n', meltPoolWidth_mm);
fprintf('Melt Pool Depth (MPD): %.4f mm\n', meltPoolDepth_mm);

% Step 10: Visualization of Heat Trail on the Top Surface

% Get the face ID for the top surface (Face 7)
topFaceID = 7;

% Find nodes on the top surface
nodesOnTopFace = findNodes(thermalModel.Mesh, 'region', 'Face', topFaceID);

% Get the x and y coordinates of these nodes
xTop = thermalModel.Mesh.Nodes(1, nodesOnTopFace);
yTop = thermalModel.Mesh.Nodes(2, nodesOnTopFace);

% Get the temperature at these nodes at the final time step
temperatureTop = results.Temperature(nodesOnTopFace, end);

% Create a grid over the x and y coordinates
xGrid = linspace(min(xTop), max(xTop), 200);
yGrid = linspace(min(yTop), max(yTop), 200);
[XGrid, YGrid] = meshgrid(xGrid, yGrid);

% Interpolate the temperature data onto the grid
F = scatteredInterpolant(xTop', yTop', temperatureTop, 'linear', 'none');
temperatureGrid = F(XGrid, YGrid);

% Step 10: Visualization using the same parameters as in Code A

figure;
pdeplot3D(thermalModel, 'ColorMapData', results.Temperature(:, end))
caxis([500, 2000]);  % Adjust color scale to match expected temperature range
title('Thermal Field in the Melt Pool');
xlabel('Scanning Direction (x) [mm]');
ylabel('Hatching Direction (y) [mm]');
zlabel('Build Direction (z) [mm]');

% Step 11: Calculate the Number of Elements in the Mesh
fprintf('Number of elements in the mesh: %d\n', numElements);

% ----------------------------
% Function Definitions
% ----------------------------

% Function for Thermal Conductivity 
%It changes significantly between the solids and liquid phase of material.
%It ensures proper phase trasition crucial for precise thermal modelling
%and adjust diffrerent material properties.
function k = thermalConductivity(region, state)
    T = state.u; % Vector of temperatures at each location
    Ts = 1563;   % Solidus temperature in K
    k = zeros(size(T));
    
    % Apply thermal conductivity based on temperature
    k(T <= Ts) = 5.331 + 0.015 * T(T <= Ts); % Solid phase
    k(T > Ts) = 30.05;                        % Liquid phase
end

% % Function for Specific Heat
% Function for Specific Heat used to calculates temperature-dependent specific heat(Cp) material for phase transition states Parameters:
%Ts (1563 K): The temperature below which the material stays solid.
%Tl (1623 K): The temperature above which the material is fully liquid.
%Lf (227,000 J/kg): The amount of heat needed to change the material from solid to liquid during melting.
% - region: Represents domain (not used here but required for function definition).
% - state.u: A vector of temperatures at each location in the domain.
function Cp = specificHeat(region, state)
    T = state.u; % Vector of temperatures
    Ts = 1563;   % Solidus temperature in K
    Tl = 1623;   % Liquidus temperature in K
    Lf = 227e3;  % Latent heat of fusion in J/kg
    Cp = zeros(size(T));

    % Solid phase
    Cp(T <= Ts) = 338.98 + 0.2437 * T(T <= Ts);

    % Liquid phase
    Cp(T >= Tl) = 735;

    % Phase change region
    between = (T > Ts) & (T < Tl);
    Cp_solid = 338.98 + 0.2437 * Ts;
    Cp_liquid = 735;
    Cp(between) = Cp_solid + ((Cp_liquid - Cp_solid) .* (T(between) - Ts) / (Tl - Ts)) + (Lf / (Tl - Ts));
end

% Laser Heat Source Function
function Qflux = laserHeatSource(region, state)
    P = 195;             % Laser power in W
    beamRadius = 0.01e-3; % Laser beam radius in m
    R = 0.01;            % Reflectivity
    A = pi * (beamRadius^2); % Beam area
    I = P / A;           % Laser intensity (W/m^2)
    scanSpeed = 0.8;   % Scanning speed in m/s

    %Calculate the laser's position along x based on the time
    %Subtracted the -4e-3/2 to get the actual simulated output based on
    %the length

    x_position = -4e-3/2 + state.time * scanSpeed;
    %Computes the X-coordinate of the laser 
    % starting at the midpoint of the domain (-4e-3/2) and advancing based on the elapsed simulation time
    % and the laser scanning speed (`scanSpeed`).

    % Calculate radial distance from the current laser position
    %The radial distance r measures how far a point in the domain is from the laser’s current position (x_position).
    % It is computed using the Euclidean distance formula:
    % Calculate radial distance from the current laser position
    r = sqrt((region.x - x_position).^2 + region.y.^2);

    % Gaussian heat flux distribution for the moving laser models the intensity of the heat flux applied by the laser.
% - The intensity diminishes exponentially as the distance r grows, 
% mimicking the behavior of a real laser where heat is strongest at the center and gradually reduces further out.
    Qflux = I * (1 - R) * exp(-2 * (r.^2) / (beamRadius^2));
end